name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SonarQube Scanner
      uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
        
    - name: Build and analyze
      run: sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL
      env:
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
